apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: http-echo
  name: http-echo
spec:
  containers:
  - image: docker.io/hashicorp/http-echo
    name: http-echo
    args: ["-text='hello world'"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
