apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: http-echo
  name: http-echo-svc
spec:
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
    nodePort: 8081
  selector:
    run: http-echo
  type: NodePort
status:
  loadBalancer: {}
